<a href="https://colab.research.google.com/github/A-R-TAQI/ml_project_01/blob/main/ml_project_06.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt
df=pd.read_csv('https://talentcocomedia.s3.amazonaws.com/ml-assets/heart-disease.csv')

In [4]:
y = df['target']

In [5]:
x = df.drop('target', axis =1)

In [7]:
from sklearn.model_selection import train_test_split

In [8]:
x_train,x_test,y_train,y_test = train_test_split(x,y,test_size = 0.3)

In [9]:
x_train.shape , x_test.shape , y_train.shape , y_test.shape

((212, 13), (91, 13), (212,), (91,))

**Logistic regression**

In [10]:
from sklearn.linear_model import LogisticRegression
model_lr = LogisticRegression(penalty ='l2' , solver ='newton-cg',C=5)

In [11]:
model_lr.fit(x_train,y_train)

LogisticRegression(C=5, solver='newton-cg')

In [12]:
yPredLr = model_lr.predict(x_test)

In [13]:
yPredLr

array([1, 1, 0, 1, 0, 1, 0, 0, 1, 1, 1, 0, 1, 0, 1, 1, 1, 1, 0, 0, 1, 1,
       1, 1, 0, 1, 0, 1, 1, 1, 1, 1, 0, 1, 0, 1, 0, 0, 1, 1, 0, 0, 0, 0,
       1, 1, 1, 1, 0, 0, 1, 1, 1, 0, 0, 1, 0, 0, 1, 1, 1, 0, 1, 0, 0, 0,
       0, 1, 1, 1, 1, 0, 1, 0, 1, 0, 1, 1, 0, 0, 0, 0, 0, 1, 0, 1, 1, 1,
       1, 1, 1])

accuracy of logistic regression

In [14]:
from sklearn.metrics import accuracy_score
acc = accuracy_score(yPredLr , y_test)
acc

0.7472527472527473

thats around 74.72 % accurate based on trained model

In [20]:
from sklearn.neighbors import KNeighborsClassifier
neigh = KNeighborsClassifier(n_neighbors=3)
neigh.fit(x_train, y_train)

KNeighborsClassifier(n_neighbors=3)

In [21]:
yPredKnn = neigh.predict(x_test)

In [22]:
yPredKnn

array([0, 1, 0, 1, 1, 1, 1, 1, 0, 0, 1, 0, 1, 0, 1, 1, 1, 1, 1, 1, 1, 0,
       0, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 1, 0, 0, 1, 1,
       1, 0, 0, 0, 1, 1, 0, 0, 1, 0, 0, 1, 0, 1, 1, 1, 1, 0, 0, 1, 0, 1,
       0, 1, 1, 1, 0, 0, 1, 1, 1, 1, 1, 0, 0, 0, 1, 1, 0, 0, 0, 1, 0, 1,
       0, 1, 1])

In [23]:
accKnn = accuracy_score(yPredKnn , y_test)

In [24]:
accKnn

0.5494505494505495

In [25]:
from sklearn.tree import DecisionTreeClassifier
dtc = DecisionTreeClassifier()
dtc.fit(x_train, y_train)

DecisionTreeClassifier()

In [26]:
yPredDtc = dtc.predict(x_test)

In [27]:
yPredDtc

array([1, 1, 0, 0, 0, 1, 0, 0, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 0, 0, 0,
       1, 0, 0, 1, 0, 1, 1, 1, 0, 0, 1, 0, 0, 1, 0, 0, 1, 1, 0, 0, 0, 1,
       1, 1, 1, 0, 1, 1, 1, 1, 1, 0, 0, 1, 0, 0, 1, 1, 0, 0, 1, 0, 0, 0,
       0, 0, 1, 0, 1, 0, 1, 1, 0, 1, 1, 1, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1,
       1, 1, 0])

In [28]:
accDtc = accuracy_score(yPredDtc , y_test)

In [29]:
accDtc

0.6813186813186813